/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface Author {
    name: string
    books: Book
}

export interface AuthorInput {
    name: string
    books?: BookInput[] | undefined
}

export interface Book {
    title: string
    authors: Author
}

export interface BookInput {
    title: string
    authors?: AuthorInput[] | undefined
}
