/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface Days {
    days: DaysDays[]
}

type DaysDays = 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday'

type Local = string

type Local2 = string

export type Ref1 = Local

export type Ref2 = Local2
