/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
// biome-ignore-all lint: this file is generated
/* eslint-disable */

export type MadeOptionalRef = Original | undefined

export type OptionalString = string | undefined

export type OptionalUnknown = unknown

export type Original = string
