/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface Team {
    id: string
    name: string
    leader: User
    members: User[]
    /**
     * @default []
     */
    tags: string[]
}

export interface User {
    id: string
    email: string
    name: string
    age: number
    roles: ('admin' | 'user' | 'guest')[]
    metadata?:
        | {
              [k: string]: unknown
          }
        | undefined
    createdAt: string
}
