/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

import { z } from 'zod'

export const CreateTodoRequest = z.object({
    title: z.string(),
})

export type CreateTodoRequest = z.infer<typeof CreateTodoRequest>

export const CreateTodoResponse = z.object({
    completed: z.boolean(),
    id: z.string(),
    title: z.string(),
})

export type CreateTodoResponse = z.infer<typeof CreateTodoResponse>

export const ListTodosResponse = z
    .object({
        completed: z.boolean(),
        id: z.string(),
        title: z.string(),
    })
    .array()

export type ListTodosResponse = z.infer<typeof ListTodosResponse>
