/**
 * Generated by @zefiros-software/therefore@v0.0.1
 * Do not manually touch this
 */
/* eslint-disable */
import AjvValidator from 'ajv'
import type { ValidateFunction } from 'ajv'

export interface Asteroid {
    type: 'asteroid'
    location: Vector
    mass: number
}

export interface Planet {
    type: 'planet'
    location: Vector
    mass: number
    population: number
    habitable: boolean
}

export type Rank = 'captain' | 'first mate' | 'officer' | 'ensign'

export interface CrewMember {
    name: string
    age: number
    rank: Rank
    home: Planet
}

export interface Ship {
    type: 'ship'
    location: Vector
    mass: number
    name: string
    crew: CrewMember[]
}

export interface Fleet {
    [k: string]: Ship | undefined
}

export type SpaceObject = Asteroid | Planet | Ship

export const SpaceObject = {
    validate: require('./schemas/space-object.schema.js') as ValidateFunction<SpaceObject>,
    get schema() {
        return SpaceObject.validate.schema
    },
    source: `${__dirname}game.schema`,
    sourceSymbol: 'spaceObject',
    is: (o: unknown): o is SpaceObject => SpaceObject.validate(o) === true,
    assert: (o: unknown) => {
        if (!SpaceObject.validate(o)) {
            throw new AjvValidator.ValidationError(SpaceObject.validate.errors ?? [])
        }
    },
} as const

type Vector = [number, number, number]
