/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { DefinedError, ValidateFunction } from 'ajv'

import { validate as GetApodResponseValidator } from './schemas/get-apod-response.schema.js'

export type GetApodResponse = unknown[]

export const GetApodResponse = {
    validate: GetApodResponseValidator as ValidateFunction<GetApodResponse>,
    get schema() {
        return GetApodResponse.validate.schema
    },
    get errors() {
        return GetApodResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is GetApodResponse => GetApodResponse.validate(o) === true,
    parse: (o: unknown): { right: GetApodResponse } | { left: DefinedError[] } => {
        if (GetApodResponse.is(o)) {
            return { right: o }
        }
        return { left: (GetApodResponse.errors ?? []) as DefinedError[] }
    },
} as const
