/* eslint-disable */
// @ts-nocheck
/**
 * Generated by Ajv https://ajv.js.org/guide/managing-schemas.html#standalone-validation-code
 */
"use strict";
/** @type {unknown} */
export const validate = validate10;export default validate10;const schema11 = {"$schema":"http://json-schema.org/draft-07/schema#","title":"Profile","type":"object","properties":{"enableTestVariable":{"type":"boolean","default":false}},"additionalProperties":true};function validate10(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;if(errors === 0){if(data && typeof data == "object" && !Array.isArray(data)){if(data.enableTestVariable === undefined){data.enableTestVariable = false;}if(typeof data.enableTestVariable !== "boolean"){validate10.errors = [{instancePath:instancePath+"/enableTestVariable",schemaPath:"#/properties/enableTestVariable/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];return false;}}else {validate10.errors = [{instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"}];return false;}}validate10.errors = vErrors;return errors === 0;};validate.schema=schema11;