/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface APIKeySecurityScheme {
    description?: string
    in: 'header' | 'query' | 'cookie'
    name: string
    type: 'apiKey'
    [k: `x-${string}`]: unknown
}

export interface AuthorizationCodeOAuthFlow {
    authorizationUrl: string
    refreshUrl?: string
    scopes: {
        [k: string]: string
    }
    tokenUrl: string
    [k: `x-${string}`]: unknown
}

export interface Callback {
    [k: string]: PathItem | unknown
    [k: `x-${string}`]: unknown
}

export interface ClientCredentialsFlow {
    refreshUrl?: string
    scopes: {
        [k: string]: string
    }
    tokenUrl: string
    [k: `x-${string}`]: unknown
}

export interface Components {
    callbacks?: {
        [k: string]: Reference | Callback
    }
    examples?: {
        [k: string]: Reference | Example
    }
    headers?: {
        [k: string]: Reference | Header
    }
    links?: {
        [k: string]: Reference | Link
    }
    parameters?: {
        [k: string]: Reference | Parameter
    }
    requestBodies?: {
        [k: string]: Reference | RequestBody
    }
    responses?: {
        [k: string]: Reference | Response
    }
    schemas?: {
        [k: string]: Schema | Reference
    }
    securitySchemes?: {
        [k: string]: Reference | SecurityScheme
    }
    [k: `x-${string}`]: unknown
}

export interface Contact {
    email?: string
    name?: string
    url?: string
    [k: `x-${string}`]: unknown
}

export interface Discriminator {
    mapping?: {
        [k: string]: string
    }
    propertyName: string
}

export interface Encoding {
    /**
     * @default false
     */
    allowReserved?: boolean
    contentType?: string
    explode?: boolean
    headers?: {
        [k: string]: Header | Reference
    }
    style?: 'form' | 'spaceDelimited' | 'pipeDelimited' | 'deepObject'
    [k: `x-${string}`]: unknown
}

export interface Example {
    description?: string
    externalValue?: string
    summary?: string
    value?: unknown
    [k: `x-${string}`]: unknown
}

export interface ExternalDocumentation {
    description?: string
    url: string
    [k: `x-${string}`]: unknown
}

export interface Header {
    /**
     * @default false
     */
    allowEmptyValue?: boolean
    /**
     * @default false
     */
    allowReserved?: boolean
    content?: {
        [k: string]: MediaType
    }
    /**
     * @default false
     */
    deprecated?: boolean
    description?: string
    example?: unknown
    examples?: {
        [k: string]: Example | Reference
    }
    explode?: boolean
    /**
     * @default false
     */
    required?: boolean
    schema?: Schema | Reference
    /**
     * @default 'simple'
     */
    style?: 'simple'
    [k: `x-${string}`]: unknown
}

export type HTTPSecurityScheme =
    | {
          scheme?: string
      }
    | {
          scheme?: unknown
      }

export interface ImplicitOAuthFlow {
    authorizationUrl: string
    refreshUrl?: string
    scopes: {
        [k: string]: string
    }
    [k: `x-${string}`]: unknown
}

export interface Info {
    contact?: Contact
    description?: string
    license?: License
    termsOfService?: string
    title: string
    version: string
    [k: `x-${string}`]: unknown
}

export interface License {
    name: string
    url?: string
    [k: `x-${string}`]: unknown
}

export interface Link {
    description?: string
    operationId?: string
    operationRef?: string
    parameters?: {
        [k: string]: unknown
    }
    requestBody?: unknown
    server?: Server
    [k: `x-${string}`]: unknown
}

export interface MediaType {
    encoding?: {
        [k: string]: Encoding
    }
    example?: unknown
    examples?: {
        [k: string]: Example | Reference
    }
    schema?: Schema | Reference
    [k: `x-${string}`]: unknown
}

export interface OAuth2SecurityScheme {
    description?: string
    flows: OAuthFlows
    type: 'oauth2'
    [k: `x-${string}`]: unknown
}

export interface OAuthFlows {
    authorizationCode?: AuthorizationCodeOAuthFlow
    clientCredentials?: ClientCredentialsFlow
    implicit?: ImplicitOAuthFlow
    password?: PasswordOAuthFlow
    [k: `x-${string}`]: unknown
}

/**
 * The description of OpenAPI v3.0.x documents, as defined by https://spec.openapis.org/oas/v3.0.3
 */
export interface OpenapiV3 {
    components?: Components
    externalDocs?: ExternalDocumentation
    info: Info
    openapi: string
    paths: Paths
    security?: SecurityRequirement[]
    servers?: Server[]
    tags?: Tag[]
    [k: `x-${string}`]: unknown
}

export interface OpenIdConnectSecurityScheme {
    description?: string
    openIdConnectUrl: string
    type: 'openIdConnect'
    [k: `x-${string}`]: unknown
}

export interface Operation {
    callbacks?: {
        [k: string]: Callback | Reference
    }
    /**
     * @default false
     */
    deprecated?: boolean
    description?: string
    externalDocs?: ExternalDocumentation
    operationId?: string
    parameters?: (Parameter | Reference)[]
    requestBody?: RequestBody | Reference
    responses: Responses
    security?: SecurityRequirement[]
    servers?: Server[]
    summary?: string
    tags?: string[]
    [k: `x-${string}`]: unknown
}

export interface Parameter {
    /**
     * @default false
     */
    allowEmptyValue?: boolean
    /**
     * @default false
     */
    allowReserved?: boolean
    content?: {
        [k: string]: MediaType
    }
    /**
     * @default false
     */
    deprecated?: boolean
    description?: string
    example?: unknown
    examples?: {
        [k: string]: Example | Reference
    }
    explode?: boolean
    in: string
    name: string
    /**
     * @default false
     */
    required?: boolean
    schema?: Schema | Reference
    style?: string
    [k: `x-${string}`]: unknown
}

export interface PasswordOAuthFlow {
    refreshUrl?: string
    scopes: {
        [k: string]: string
    }
    tokenUrl: string
    [k: `x-${string}`]: unknown
}

export interface PathItem {
    $ref?: string
    delete?: Operation
    description?: string
    get?: Operation
    head?: Operation
    options?: Operation
    parameters?: (Parameter | Reference)[]
    patch?: Operation
    post?: Operation
    put?: Operation
    servers?: Server[]
    summary?: string
    trace?: Operation
    [k: `x-${string}`]: unknown
}

export interface Paths {
    [k: `/${string}`]: PathItem
    [k: `x-${string}`]: unknown
}

export interface Reference {
    $ref: string
}

export interface RequestBody {
    content: {
        [k: string]: MediaType
    }
    description?: string
    /**
     * @default false
     */
    required?: boolean
    [k: `x-${string}`]: unknown
}

export interface Response {
    content?: {
        [k: string]: MediaType
    }
    description: string
    headers?: {
        [k: string]: Header | Reference
    }
    links?: {
        [k: string]: Link | Reference
    }
    [k: `x-${string}`]: unknown
}

export interface Responses {
    default?: Response | Reference
    [k: string]: Response | Reference | unknown
    [k: `x-${string}`]: unknown
}

export interface Schema {
    /**
     * @default true
     */
    additionalProperties?: Schema | Reference | boolean
    allOf?: (Schema | Reference)[]
    anyOf?: (Schema | Reference)[]
    default?: unknown
    /**
     * @default false
     */
    deprecated?: boolean
    description?: string
    discriminator?: Discriminator
    enum?: [unknown, ...unknown[]]
    example?: unknown
    /**
     * @default false
     */
    exclusiveMaximum?: boolean
    /**
     * @default false
     */
    exclusiveMinimum?: boolean
    externalDocs?: ExternalDocumentation
    format?: string
    items?: Schema | Reference
    maximum?: number
    maxItems?: number
    maxLength?: number
    maxProperties?: number
    minimum?: number
    /**
     * @default 0
     */
    minItems?: number
    /**
     * @default 0
     */
    minLength?: number
    /**
     * @default 0
     */
    minProperties?: number
    multipleOf?: number
    not?: Schema | Reference
    /**
     * @default false
     */
    nullable?: boolean
    oneOf?: (Schema | Reference)[]
    pattern?: string
    properties?: {
        [k: string]: Schema | Reference
    }
    /**
     * @default false
     */
    readOnly?: boolean
    required?: [string, ...string[]]
    title?: string
    type?: 'array' | 'boolean' | 'integer' | 'number' | 'object' | 'string'
    /**
     * @default false
     */
    uniqueItems?: boolean
    /**
     * @default false
     */
    writeOnly?: boolean
    xml?: XML
    [k: `x-${string}`]: unknown
}

export interface SecurityRequirement {
    [k: string]: string[]
}

export type SecurityScheme = APIKeySecurityScheme | HTTPSecurityScheme | OAuth2SecurityScheme | OpenIdConnectSecurityScheme

export interface Server {
    description?: string
    url: string
    variables?: {
        [k: string]: ServerVariable
    }
    [k: `x-${string}`]: unknown
}

export interface ServerVariable {
    default: string
    description?: string
    enum?: string[]
    [k: `x-${string}`]: unknown
}

export interface Tag {
    description?: string
    externalDocs?: ExternalDocumentation
    name: string
    [k: `x-${string}`]: unknown
}

export interface XML {
    /**
     * @default false
     */
    attribute?: boolean
    name?: string
    namespace?: string
    prefix?: string
    /**
     * @default false
     */
    wrapped?: boolean
    [k: `x-${string}`]: unknown
}
