/**
 * Generated by Ajv https://ajv.js.org/guide/managing-schemas.html#standalone-validation-code 
 * eslint-disable
 */
const a={$schema:"http://json-schema.org/draft-07/schema#",title:"Defaults",type:"object",properties:{foo:{type:"boolean",default:!1}},additionalProperties:!0};function o(e,{instancePath:r="",parentData:f,parentDataProperty:p,rootData:l=e}={}){let s=null,t=0;if(t===0)if(e&&typeof e=="object"&&!Array.isArray(e)){if(e.foo===void 0&&(e.foo=!1),typeof e.foo!="boolean")return o.errors=[{instancePath:r+"/foo",schemaPath:"#/properties/foo/type",keyword:"type",params:{type:"boolean"},message:"must be boolean"}],!1}else return o.errors=[{instancePath:r,schemaPath:"#/type",keyword:"type",params:{type:"object"},message:"must be object"}],!1;return o.errors=s,t===0}o.schema=a;export{o as validate10};
