import { action } from './action.js'
import { command } from './command.js'
import { icon, uri } from './icon.js'

import { $array, $boolean, $enum, $object, $ref, $string, $validator } from '../../src/index.js'
import { $const } from '../../src/lib/primitives/const/const.js'
import { $record } from '../../src/lib/primitives/record/record.js'
import { $unknown } from '../../src/lib/primitives/unknown/unknown.js'

// https://json.schemastore.org/chrome-manifest

const version_string = $string({ name: 'versionString' }).regex(/^(?:\d{1,5}\.){0,3}\d{1,5}$/)

const page = $ref(uri, { name: 'page' })

const scripts = $ref(uri)
    .array({
        name: 'scripts',
    })
    .set()
    .nonempty()

const content_security_policy = $string({
    name: 'contentSecurityPolicy',
    //format: 'content-security-policy'
})
    .describe(
        'This introduces some fairly strict policies that will make extensions more secure by default, and provides you with the ability to create and enforce rules governing the types of content that can be loaded and executed by your extensions and applications.',
    )
    .default("script-src 'self'; object-src 'self'")

const glob_pattern = $string({
    name: 'glob pattern',
    //format: 'glob-pattern'
})

const match_pattern = $string({
    name: 'match pattern',
    //format: 'match-pattern'
}).regex(/^((\\*|http|https|file|ftp|chrome-extension):\/\/(\*|\*\.[^\/\*]+|[^\/\*]+)?(\/.*))|<all_urls>$/)

const mime_type = $string({
    name: 'mime_type',
    //format: 'mime-type',
}).regex(/^(?:application|audio|image|message|model|multipart|text|video)\/[-+.\\w]+$/)

const permissions = $string({
    //format: 'permission'
})
    .array({
        name: 'permissions',
    })
    .set()

export const extension = $validator(
    $object({
        manifest_version: $const(2).describe(
            'One integer specifying the version of the manifest file format your package requires.',
        ),
        name: $string().maxLength(45).describe('The name of the extension'),
        version: $ref(version_string).describe('One to four dot-separated integers identifying the version of this extension.'),
        default_locale: $string()
            .default('en')
            .describe('Specifies the subdirectory of _locales that contains the default strings for this extension.'),
        description: $string().maxLength(132).describe('A plain text description of the extension'),
        icons: $object(
            {
                '16': $ref(icon).describe("Used as the favicon for an extension's pages and infobar."),
                '48': $ref(icon).describe('Used on the extension management page (chrome://extensions).'),
                '128': $ref(icon).describe('Used during installation and in the Chrome Web Store.'),
                '256': $ref(icon).describe('Used during installation and in the Chrome Web Store.'),
            },
            {
                // minProperties: 1,
            },
        ).describe(
            'One or more icons that represent the extension, app, or theme. Recommended format: PNG; also BMP, GIF, ICO, JPEG.',
        ),
        browser_action: $ref(action).describe(
            'Use browser actions to put icons in the main Google Chrome toolbar, to the right of the address bar. In addition to its icon, a browser action can also have a tooltip, a badge, and a popup.',
        ),
        page_action: $ref(action).describe(
            "Use the chrome.pageAction API to put icons inside the address bar. Page actions represent actions that can be taken on the current page, but that aren't applicable to all pages.",
        ),
        background: $object(
            {
                persistent: $boolean()
                    .default(true)
                    .describe('When false, makes the background page an event page (loaded only when needed).'),
                page: $ref(uri).default('background.html').describe('Specify the HTML of the background page.'),
                scripts: $ref(scripts)
                    .describe(
                        'A background page will be generated by the extension system that includes each of the files listed in the scripts property.',
                    )
                    .default(['background.js']),
            },
            {
                // dependencies: {
                //     page: { not: { required: ['scripts'] } },
                //     scripts: { not: { required: ['page'] } },
                // },
            },
        ).describe(
            'The background page is an HTML page that runs in the extension process. It exists for the lifetime of your extension, and only one instance of it at a time is active.',
        ),
        chrome_url_overrides: $object(
            {
                bookmarks: page
                    .reference()
                    .default('bookmarks.html')
                    .describe(
                        'The page that appears when the user chooses the Bookmark Manager menu item from the Chrome menu or, on Mac, the Bookmark Manager item from the Bookmarks menu. You can also get to this page by entering the URL chrome://bookmarks.',
                    ),
                history: page
                    .reference()
                    .default('history.html')
                    .describe(
                        'The page that appears when the user chooses the History menu item from the Chrome menu or, on Mac, the Show Full History item from the History menu. You can also get to this page by entering the URL chrome://history.',
                    ),
                newtab: page
                    .reference()
                    .default('newtab.html')
                    .describe(
                        'The page that appears when the user creates a new tab or window. You can also get to this page by entering the URL chrome://newtab.',
                    ),
            },
            {
                // maxProperties: 1,
            },
        ).describe(
            'Override pages are a way to substitute an HTML file from your extension for a page that Google Chrome normally provides.',
        ),
        commands: $record(command.reference(), {
            // patternProperties: {
            //     '.*': { $ref: '#/definitions/command' },
            //     '^_execute_browser_action$': { $ref: '#/definitions/command' },
            //     '^_execute_page_action$': { $ref: '#/definitions/command' },
            // },
        }).describe(
            'Use the commands API to add keyboard shortcuts that trigger actions in your extension, for example, an action to open the browser action or send a command to the extension.',
        ),
        content_scripts: $object({
            //required: ['matches'],
            matches: match_pattern
                .reference()
                .array()
                .minItems(1)
                .set()
                .describe('Specifies which pages this content script will be injected into.'),

            exclude_matches: match_pattern
                .reference()
                .array()
                .set()
                .describe('Excludes pages that this content script would otherwise be injected into.'),
            css: uri
                .reference()
                .array()
                .set()
                .describe(
                    'The list of CSS files to be injected into matching pages. These are injected in the order they appear in this array, before any DOM is constructed or displayed for the page.',
                ),
            js: scripts
                .reference()
                .describe(
                    'The list of JavaScript files to be injected into matching pages. These are injected in the order they appear in this array.',
                ),
            run_at: $enum(['document_start', 'document_end', 'document_idle'])
                .default('document_idle')
                .describe('Controls when the files in js are injected.'),
            all_frames: $boolean()
                .default(false)
                .describe('Controls whether the content script runs in all frames of the matching page, or only the top frame.'),
            include_globs: glob_pattern
                .reference()
                .array()
                .set()
                .describe(
                    'Applied after matches to include only those URLs that also match this glob. Intended to emulate the @include Greasemonkey keyword.',
                ),
            exclude_globs: glob_pattern
                .reference()
                .array()
                .set()
                .describe(
                    'Applied after matches to exclude URLs that match this glob. Intended to emulate the @exclude Greasemonkey keyword.',
                ),
            match_about_blank: $boolean()
                .default(false)
                .describe('Whether to insert the content script on about:blank and about:srcdoc.'),
        })
            .array()
            .set()
            .nonempty()
            .describe('Content scripts are JavaScript files that run in the context of web pages.'),
        content_security_policy: content_security_policy.reference(),
        devtools_page: page
            .reference()
            .describe(
                'A DevTools extension adds functionality to the Chrome DevTools. It can add new UI panels and sidebars, interact with the inspected page, get information about network requests, and more.',
            ),
        externally_connectable: $object({
            ids: $array($string).describe(
                'The IDs of extensions or apps that are allowed to connect. If left empty or unspecified, no extensions or apps can connect.',
            ),
            matches: $array($string).describe(
                'The URL patterns for web pages that are allowed to connect. This does not affect content scripts. If left empty or unspecified, no web pages can connect.',
            ),
            accepts_tls_channel_id: $boolean()
                .default(false)
                .describe(
                    "Indicates that the extension would like to make use of the TLS channel ID of the web page connecting to it. The web page must also opt to send the TLS channel ID to the extension via setting includeTlsChannelId to true in runtime.connect's connectInfo or runtime.sendMessage's options.",
                ),
        }).describe(
            'Declares which extensions, apps, and web pages can connect to your extension via runtime.connect and runtime.sendMessage.',
        ),
        file_browser_handlers: $array(
            $object({
                id: $string().describe('Used by event handling code to differentiate between multiple file handlers'),
                default_title: $string().describe('What the button will display.'),
                file_filters: $array($string).nonempty().describe('Filetypes to match.'),
            }),
        )
            .nonempty()
            .describe('You can use this API to enable users to upload files to your website.'),
        homepage_url: uri.reference().describe('The URL of the homepage for this extension.'),
        incognito: $enum(['spanning', 'split', 'not_allowed'])
            .default('spanning')
            .describe('Specify how this extension will behave if allowed to run in incognito mode.'),
        input_components: $object({
            name: $string,
            type: $string,
            id: $string,
            description: $string,
            language: $string,
            layouts: $array($string),
        })
            .array()
            .describe('Allows your extension to handle keystrokes, set the composition, and manage the candidate window.'),
        key: $string().describe(
            'This value can be used to control the unique ID of an extension, app, or theme when it is loaded during development.',
        ),
        minimum_chrome_version: version_string
            .reference()
            .describe('The version of Chrome that your extension, app, or theme requires, if any.'),
        nacl_modules: $object({
            path: uri
                .reference()
                .describe('The location of a Native Client manifest (a .nmf file) within the extension directory.'),
            mime_type: mime_type
                .reference()
                .describe('The MIME type for which the Native Client module will be registered as content handler.'),
        })
            .array()
            .set()
            .nonempty()
            .describe('One or more mappings from MIME types to the Native Client module that handles each type.'),
        oauth2: $object({
            client_id: $string().describe('You need to register your app in the Google APIs Console to get the client ID.'),
            scopes: $array($string).nonempty(),
        }).describe(
            'Use the Chrome Identity API to authenticate users: the getAuthToken for users logged into their Google Account and the launchWebAuthFlow for users logged into a non-Google account.',
        ),
        offline_enabled: $boolean().describe(
            'Whether the app or extension is expected to work offline. When Chrome detects that it is offline, apps with this field set to true will be highlighted on the New Tab page.',
        ),
        omnibox: $object({
            keyword: $string().describe('The keyward that will trigger your extension.'),
        }).describe(
            "The omnibox API allows you to register a keyword with Google Chrome's address bar, which is also known as the omnibox.",
        ),
        optional_permissions: permissions
            .reference()
            .describe(
                'Use the chrome.permissions API to request declared optional permissions at run time rather than install time, so users understand why the permissions are needed and grant only those that are necessary.',
            ),
        options_page: page
            .reference()
            .default('options.html')
            .describe(
                'To allow users to customize the behavior of your extension, you may wish to provide an options page. If you do, a link to it will be provided from the extensions management page at chrome://extensions. Clicking the Options link opens a new tab pointing at your options page.',
            ),

        options_ui: $object({
            page: $string().describe("The path to your options page, relative to your extension's root."),
            chrome_style: $boolean()
                .default(true)
                .optional()
                .describe(
                    'If true, a Chrome user agent stylesheet will be applied to your options page. The default value is false, but we recommend you enable it for a consistent UI with Chrome.',
                ),
            open_in_tab: $boolean()
                .default(false)
                .describe(
                    "If true, your extension's options page will be opened in a new tab rather than embedded in chrome://extensions. The default is false, and we recommend that you don't change it. This is only useful to delay the inevitable deprecation of the old options UI! It will be removed soon, so try not to use it. It will break.",
                )
                .optional(),
        }).describe(
            'To allow users to customize the behavior of your extension, you may wish to provide an options page. If you do, an Options link will be shown on the extensions management page at chrome://extensions which opens a dialogue containing your options page.',
        ),
        permissions: permissions
            .reference()
            .describe(
                'Permissions help to limit damage if your extension or app is compromised by malware. Some permissions are also displayed to users before installation, as detailed in Permission Warnings.',
            ),
        requirements: $object({
            '3D': $object({
                features: $enum(['webgl'])
                    .array()
                    .nonempty()
                    .set()
                    .describe('List of the 3D-related features your app requires.'),
            }).describe("The '3D' requirement denotes GPU hardware acceleration."),
            plugins: $object({
                npapi: $boolean().default(true),
            }).describe(
                "Indicates if an app or extension requires NPAPI to run. This requirement is enabled by default when the manifest includes the 'plugins' field.",
            ),
        }).describe(
            'Technologies required by the app or extension. Hosting sites such as the Chrome Web Store may use this list to dissuade users from installing apps or extensions that will not work on their computer.',
        ),
        sandbox: $object({
            pages: page.reference().array().nonempty().set(),
            content_security_policy: content_security_policy.reference().default('sandbox allow-scripts allow-forms').optional(),
        }).describe(
            'Defines an collection of app or extension pages that are to be served in a sandboxed unique origin, and optionally a Content Security Policy to use with them.',
        ),
        short_name: $string()
            .maxLength(12)
            .describe('The short name is typically used where there is insufficient space to display the full name.'),
        update_url: uri
            .reference()
            .describe(
                'If you publish using the Chrome Developer Dashboard, ignore this field. If you host your own extension or app: URL to an update manifest XML file.',
            ),
        tts_engine: $object({
            voices: $object({
                voice_name: $string().describe('Identifies the name of the voice and the engine used.'),
                lang: $string().describe(
                    'Almost always, a voice can synthesize speech in just a single language. When an engine supports more than one language, it can easily register a separate voice for each language.',
                ),
                gender: $string().describe(
                    'If your voice corresponds to a male or female voice, you can use this parameter to help clients choose the most appropriate voice for their application.',
                ),
                event_types: $enum(['start', 'word', 'sentence', 'marker', 'end', 'error'])
                    .array()
                    .nonempty()
                    .set()
                    .optional()
                    .describe('Events sent to update the client on the progress of speech synthesis.'),
            })
                .array()
                .nonempty()
                .set()
                .describe('Voices the extension can synthesize.'),
            version_name: $string().describe(
                'In addition to the version field, which is used for update purposes, version_name can be set to a descriptive version string and will be used for display purposes if present.',
            ),
            web_accessible_resources: uri
                .reference()
                .array()
                .nonempty()
                .set()
                .describe(
                    'An array of strings specifying the paths (relative to the package root) of packaged resources that are expected to be usable in the context of a web page.',
                ),
            chrome_settings_overrides: $unknown,
            content_pack: $unknown,
            current_locale: $unknown,
            import: $unknown,
            platforms: $unknown,
            signature: $unknown,
            spellcheck: $unknown,
            storage: $unknown,
            system_indicator: $unknown,
        }).describe('Register itself as a speech engine.'),
    }).describe('JSON schema for Google Chrome extension manifest files'),
)
