/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { Episode } from './episode.type.js'
import type { CharacterArgs } from './input.type.js'

export type AppearsInResolverType = Episode[]

/**
 * Which movies they appear in.
 */
export type AppearsInResolver = (args: AppearsInResolverArgs) => AppearsInResolverType

export type AppearsInResolverArgs = CharacterArgs

export interface Character {
    /**
     * The id of the character
     */
    id: string
    /**
     * The name of the character
     */
    name: string
}

/**
 * The friends of the character, or an empty list if they have none.
 */
export type FriendsResolverType = Character[]

/**
 * The friends of the character, or an empty list if they have none.
 */
export type FriendsResolver = () => FriendsResolverType
