/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

/**
 * A mechanical creature in the Star Wars universe.
 */
export interface Droid {
    /**
     * The id of the character
     */
    id: string
    /**
     * The name of the character
     */
    name: string
}

export type PrimaryFunctionResolverType = string

/**
 * The primary function of the droid.
 */
export type PrimaryFunctionResolver = () => PrimaryFunctionResolverType
