/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

import type { Character } from './character.type.js'

/**
 * A mechanical creature in the Star Wars universe.
 */
export type Droid = Character & {}

/**
 * The primary function of the droid.
 */
export type PrimaryFunctionResolver = () => PrimaryFunctionResolverType

export type PrimaryFunctionResolverType = string
