/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

/**
 * One of the films in the Star Wars Trilogy
 */
export type Episode = 'NEWHOPE' | 'EMPIRE' | 'JEDI'

export type MoreEpisodes = Episode | 'OTHER'
