/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

import type { Character } from './character.type.js'

/**
 * The home planet of the human, or null if unknown.
 */
export type HomePlanetResolver = () => HomePlanetResolverType

export type HomePlanetResolverType = string | undefined

/**
 * A humanoid creature in the Star Wars universe.
 */
export type Human = Character & {}
