/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { DefinedError, ValidateFunction } from 'ajv'

import { validate as ValidatedUserValidator } from './schemas/user-schema.schema.js'

export interface Attributes {
    [k: string]: string | undefined
}

export type Email = string

export type Users = ValidatedUser[]

export const ValidatedUser = {
    validate: ValidatedUserValidator as ValidateFunction<ValidatedUser>,
    get schema() {
        return ValidatedUser.validate.schema
    },
    get errors() {
        return ValidatedUser.validate.errors ?? undefined
    },
    is: (o: unknown): o is ValidatedUser => ValidatedUser.validate(o) === true,
    parse: (o: unknown): { right: ValidatedUser } | { left: DefinedError[] } => {
        if (ValidatedUser.is(o)) {
            return { right: o }
        }
        return { left: (ValidatedUser.errors ?? []) as DefinedError[] }
    },
} as const

export interface ValidatedUser {
    id: number
    username: string
    email: Email
    attributes: Attributes
}
