/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

import type { Name } from './validator.type.js'

export type HairReference = {
    color: string
    length: number
}

export type Pet = {
    category?:
        | {
              id?: number | undefined
              name?: string | undefined
          }
        | undefined
    id?: number | undefined
    name: string
    photoUrls: string[]
    /**
     * pet status in the store
     */
    status?: 'available' | 'pending' | 'sold' | undefined
    tags?:
        | {
              id?: number | undefined
              name?: string | undefined
          }[]
        | undefined
}

export type User = {
    name: string
    age: number
    pet?: Pet | undefined
    hair?: HairReference | undefined
    tag: {
        id?: number | undefined
        name?: string | undefined
    }
}

export type ObjectSchemaZod = {
    name: Name
    age: number
}
