/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import AjvValidator from 'ajv'
import type { ValidateFunction } from 'ajv'

export interface Pet {
    id?: number
    name: string
    category?: Category
    photoUrls: string[]
    tags?: Tag[]
    /**
     * pet status in the store
     */
    status?: 'available' | 'pending' | 'sold'
}

export const Pet = {
    validate: (await import('./schemas/pet.schema.js')).validate10 as unknown as ValidateFunction<Pet>,
    get schema() {
        return Pet.validate.schema
    },
    get errors() {
        return Pet.validate.errors ?? undefined
    },
    is: (o: unknown): o is Pet => Pet.validate(o) === true,
    assert: (o: unknown) => {
        if (!Pet.validate(o)) {
            throw new AjvValidator.ValidationError(Pet.errors ?? [])
        }
    },
} as const

export type FindPetsByStatusResponse = Pet[]

export const FindPetsByStatusResponse = {
    validate: (await import('./schemas/find-pets-by-status-response.schema.js'))
        .validate10 as unknown as ValidateFunction<FindPetsByStatusResponse>,
    get schema() {
        return FindPetsByStatusResponse.validate.schema
    },
    get errors() {
        return FindPetsByStatusResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is FindPetsByStatusResponse => FindPetsByStatusResponse.validate(o) === true,
} as const

export type FindPetsByTagsResponse = Pet[]

export const FindPetsByTagsResponse = {
    validate: (await import('./schemas/find-pets-by-tags-response.schema.js'))
        .validate10 as unknown as ValidateFunction<FindPetsByTagsResponse>,
    get schema() {
        return FindPetsByTagsResponse.validate.schema
    },
    get errors() {
        return FindPetsByTagsResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is FindPetsByTagsResponse => FindPetsByTagsResponse.validate(o) === true,
} as const

export interface ApiResponse {
    code?: number
    type?: string
    message?: string
}

export const ApiResponse = {
    validate: (await import('./schemas/api-response.schema.js')).validate10 as unknown as ValidateFunction<ApiResponse>,
    get schema() {
        return ApiResponse.validate.schema
    },
    get errors() {
        return ApiResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is ApiResponse => ApiResponse.validate(o) === true,
} as const

export interface GetInventoryResponse {
    [k: string]: number
}

export const GetInventoryResponse = {
    validate: (await import('./schemas/get-inventory-response.schema.js'))
        .validate10 as unknown as ValidateFunction<GetInventoryResponse>,
    get schema() {
        return GetInventoryResponse.validate.schema
    },
    get errors() {
        return GetInventoryResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is GetInventoryResponse => GetInventoryResponse.validate(o) === true,
} as const

export interface Order {
    id?: number
    petId?: number
    quantity?: number
    shipDate?: string
    /**
     * Order Status
     */
    status?: 'placed' | 'approved' | 'delivered'
    complete?: boolean
}

export const Order = {
    validate: (await import('./schemas/order.schema.js')).validate10 as unknown as ValidateFunction<Order>,
    get schema() {
        return Order.validate.schema
    },
    get errors() {
        return Order.validate.errors ?? undefined
    },
    is: (o: unknown): o is Order => Order.validate(o) === true,
    assert: (o: unknown) => {
        if (!Order.validate(o)) {
            throw new AjvValidator.ValidationError(Order.errors ?? [])
        }
    },
} as const

export interface User {
    id?: number
    username?: string
    firstName?: string
    lastName?: string
    email?: string
    password?: string
    phone?: string
    /**
     * User Status
     */
    userStatus?: number
}

export const User = {
    validate: (await import('./schemas/user.schema.js')).validate10 as unknown as ValidateFunction<User>,
    get schema() {
        return User.validate.schema
    },
    get errors() {
        return User.validate.errors ?? undefined
    },
    is: (o: unknown): o is User => User.validate(o) === true,
    assert: (o: unknown) => {
        if (!User.validate(o)) {
            throw new AjvValidator.ValidationError(User.errors ?? [])
        }
    },
} as const

export type CreateUsersWithListInputRequest = User[]

export const CreateUsersWithListInputRequest = {
    validate: (await import('./schemas/create-users-with-list-input-request.schema.js'))
        .validate10 as unknown as ValidateFunction<CreateUsersWithListInputRequest>,
    get schema() {
        return CreateUsersWithListInputRequest.validate.schema
    },
    get errors() {
        return CreateUsersWithListInputRequest.validate.errors ?? undefined
    },
    is: (o: unknown): o is CreateUsersWithListInputRequest => CreateUsersWithListInputRequest.validate(o) === true,
    assert: (o: unknown) => {
        if (!CreateUsersWithListInputRequest.validate(o)) {
            throw new AjvValidator.ValidationError(CreateUsersWithListInputRequest.errors ?? [])
        }
    },
} as const

export type LoginUserResponse = string

export const LoginUserResponse = {
    validate: (await import('./schemas/login-user-response.schema.js'))
        .validate10 as unknown as ValidateFunction<LoginUserResponse>,
    get schema() {
        return LoginUserResponse.validate.schema
    },
    get errors() {
        return LoginUserResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is LoginUserResponse => LoginUserResponse.validate(o) === true,
} as const

export interface Category {
    id?: number
    name?: string
}

export interface Tag {
    id?: number
    name?: string
}
