/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface CreatePetInput {
    ownerId: string
    id: number
    category?:
        | {
              id?: number | undefined
              name?: string | undefined
          }
        | undefined
    name: string
    photoUrls: string[]
    /**
     * pet status in the store
     */
    status?: 'available' | 'pending' | 'sold' | undefined
    tags?:
        | {
              id?: number | undefined
              name?: string | undefined
          }[]
        | undefined
    createdAt?: string | undefined
    updatedAt?: string | undefined
}

export interface Entity {
    pk: string
    sk: string
    entityType: string
    createdAt: string
    updatedAt: string
}

export interface GetPetInput {
    ownerId: string
    id: number
}

export interface ListCategoriesByOwnerInput {
    ownerId: string
}

export interface ListPetEntityCollectionInput {
    ownerId: string
}

export interface ListPetsInput {}

export interface ListPetsByOwnerInput {
    ownerId: string
}

export interface ListPetsBySkInput {
    id: number
}

export interface UpdatePetNameInput {
    ownerId: string
    id: number
    name: string
}

export interface UpdatePetName1Input {
    ownerId: string
    id: number
    name: string
    category: {
        id?: number | undefined
        name?: string | undefined
    }
}

export interface UpsertPetNameInput {
    ownerId: string
    id: number
    name: string
}
