/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import AjvValidator from 'ajv'
import type { ValidateFunction } from 'ajv'

export type Size = 'XS' | 'S' | 'M' | 'L' | 'XL'

export interface CartItem {
    id: string
    name: string
    price: number
    size?: Size
}

export const CartItem = {
    validate: require('./schemas/cart-item.schema.js') as ValidateFunction<CartItem>,
    get schema() {
        return CartItem.validate.schema
    },
    get errors() {
        return CartItem.validate.errors ?? undefined
    },
    is: (o: unknown): o is CartItem => CartItem.validate(o) === true,
    assert: (o: unknown) => {
        if (!CartItem.validate(o)) {
            throw new AjvValidator.ValidationError(CartItem.errors ?? [])
        }
    },
} as const
