/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface CreateCustomerInput {
    customerId: string
    creationDate?: string | undefined
    updateDate?: string | undefined
    email: string
    fullName: string
    userPreferences: unknown
}

export interface GetCustomerInput {
    customerId: string
}

export interface Shape {
    customerId: string
    sk: string
    creationDate: string
    updateDate: string
}
