/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface CreateBicycleInput {
    Id: number
    Price: number
    ProductCategory: 'Bicycle'
    Title?: string | undefined
    Dimensions?: string | undefined
    InStock?: boolean | undefined
    QuantityOnHand?: number | null | undefined
    RelatedItems?: number[] | undefined
    Pictures?:
        | {
              FrontView: string
              RearView: string
              SideView: string
          }
        | undefined
    ProductReviews?:
        | {
              FiveStar: string[]
              OneStar: string[]
          }
        | undefined
    Comment?: string | undefined
    'Safety.Warning'?: string | undefined
    Description: string
    BicycleType: string
    Brand: string
    Color: string[]
}

export interface CreateBookInput {
    Id: number
    Price: number
    ProductCategory: 'Book'
    Title?: string | undefined
    Dimensions?: string | undefined
    InStock?: boolean | undefined
    QuantityOnHand?: number | null | undefined
    RelatedItems?: number[] | undefined
    Pictures?:
        | {
              FrontView: string
              RearView: string
              SideView: string
          }
        | undefined
    ProductReviews?:
        | {
              FiveStar: string[]
              OneStar: string[]
          }
        | undefined
    Comment?: string | undefined
    'Safety.Warning'?: string | undefined
    ISBN: string
    Authors: string[]
    PageCount: number
    InPublication: boolean
}

export interface CreateHomeImprovementInput {
    Id: number
    Price: number
    ProductCategory: 'Home Improvement'
    Title?: string | undefined
    Dimensions?: string | undefined
    InStock?: boolean | undefined
    QuantityOnHand?: number | null | undefined
    RelatedItems?: number[] | undefined
    Pictures?:
        | {
              FrontView: string
              RearView: string
              SideView: string
          }
        | undefined
    ProductReviews?:
        | {
              FiveStar: string[]
              OneStar: string[]
          }
        | undefined
    Comment?: string | undefined
    'Safety.Warning'?: string | undefined
}

export interface GetBicycleProjectionInput {
    Id: number
}

export interface GetBookReservedKeywordsInput {
    Id: number
}

export interface GetBookSpecialCharactersInput {
    Id: number
}

export interface GetHomeImprovementInput {
    Id: number
}

export interface GetProductsByColourAndPriceInput {
    color: string
    price: number
}

export type UpdateHomeImprovementInput = {
    Id: number
} & {
    ProductCategory: 'Home Improvement'
    Price: number
}
