/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

import { z } from 'zod'

export const HomeImprovementEntity = z
    .object({
        Id: z.number(),
        Price: z.number(),
        ProductCategory: z.enum(['Book', 'Bicycle', 'Home Improvement']),
        Title: z.string().optional(),
        Dimensions: z.string().optional(),
        InStock: z.boolean().optional(),
        QuantityOnHand: z.number().nullable().optional(),
        RelatedItems: z.number().array().optional(),
        Pictures: z
            .object({
                FrontView: z.string().url(),
                RearView: z.string().url(),
                SideView: z.string().url(),
            })
            .optional(),
        ProductReviews: z
            .object({
                FiveStar: z.string().array(),
                OneStar: z.string().array(),
            })
            .optional(),
        Comment: z.string().optional(),
        'Safety.Warning': z.string().optional(),
    })
    .merge(
        z.object({
            ProductCategory: z.literal('Home Improvement'),
        }),
    )

export type HomeImprovementEntity = z.infer<typeof HomeImprovementEntity>

export const BicycleEntity = z
    .object({
        Id: z.number(),
        Price: z.number(),
        ProductCategory: z.enum(['Book', 'Bicycle', 'Home Improvement']),
        Title: z.string().optional(),
        Dimensions: z.string().optional(),
        InStock: z.boolean().optional(),
        QuantityOnHand: z.number().nullable().optional(),
        RelatedItems: z.number().array().optional(),
        Pictures: z
            .object({
                FrontView: z.string().url(),
                RearView: z.string().url(),
                SideView: z.string().url(),
            })
            .optional(),
        ProductReviews: z
            .object({
                FiveStar: z.string().array(),
                OneStar: z.string().array(),
            })
            .optional(),
        Comment: z.string().optional(),
        'Safety.Warning': z.string().optional(),
    })
    .merge(
        z.object({
            Description: z.string(),
            BicycleType: z.string(),
            Brand: z.string(),
            Color: z.string().array(),
            ProductCategory: z.literal('Bicycle'),
        }),
    )

export type BicycleEntity = z.infer<typeof BicycleEntity>

export const BookEntity = z
    .object({
        Id: z.number(),
        Price: z.number(),
        ProductCategory: z.enum(['Book', 'Bicycle', 'Home Improvement']),
        Title: z.string().optional(),
        Dimensions: z.string().optional(),
        InStock: z.boolean().optional(),
        QuantityOnHand: z.number().nullable().optional(),
        RelatedItems: z.number().array().optional(),
        Pictures: z
            .object({
                FrontView: z.string().url(),
                RearView: z.string().url(),
                SideView: z.string().url(),
            })
            .optional(),
        ProductReviews: z
            .object({
                FiveStar: z.string().array(),
                OneStar: z.string().array(),
            })
            .optional(),
        Comment: z.string().optional(),
        'Safety.Warning': z.string().optional(),
    })
    .merge(
        z.object({
            ISBN: z.string(),
            Authors: z.string().array(),
            PageCount: z.number(),
            InPublication: z.boolean(),
            ProductCategory: z.literal('Book'),
        }),
    )

export type BookEntity = z.infer<typeof BookEntity>

export const GetBicycleProjectionResult = BicycleEntity.pick({
    Description: true,
})

export type GetBicycleProjectionResult = z.infer<typeof GetBicycleProjectionResult>

export const GetBookReservedKeywordsResult = BookEntity.pick({
    Comment: true,
})

export type GetBookReservedKeywordsResult = z.infer<typeof GetBookReservedKeywordsResult>

export const GetBookSpecialCharactersResult = BookEntity.pick({
    'Safety.Warning': true,
})

export type GetBookSpecialCharactersResult = z.infer<typeof GetBookSpecialCharactersResult>
