/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

import type { DynamoDBDocument } from '@aws-sdk/lib-dynamodb'

export class StaticDataEntityClient {
    public entityType = 'StaticData' as const
    public table: SkiResortTable

    public constructor({ table }: { table: SkiResortTable }) {
        this.table = table
    }
}

export class ResortsEntityClient {
    public entityType = 'Resort' as const
    public table: SkiResortTable

    public constructor({ table }: { table: SkiResortTable }) {
        this.table = table
    }
}

export class SkiLiftsEntityClient {
    public entityType = 'SkiLift' as const
    public table: SkiResortTable

    public constructor({ table }: { table: SkiResortTable }) {
        this.table = table
    }
}

export class SkiResortTable {
    public tableName: string
    public client: DynamoDBDocument

    public constructor({ client, tableName }: { client: DynamoDBDocument; tableName: string }) {
        this.client = client
        this.tableName = tableName
    }
}
