/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
// biome-ignore-all lint: this file is generated
/* eslint-disable */

import { z } from 'zod'

export const GetApodResponse = z.unknown().array()

export type GetApodResponse = z.infer<typeof GetApodResponse>
