/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import { z } from 'zod'

export const GetApodResponse = z.array(z.unknown())

export type GetApodResponse = z.infer<typeof GetApodResponse>
