/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
// biome-ignore-all lint: this file is generated
/* eslint-disable */

import type { IncomingHttpHeaders } from 'node:http'

import type { DefinedError } from 'ajv'
import type { CancelableRequest, Got, Options, OptionsInit, Response } from 'got'
import { got } from 'got'

import {
    ArrayWithStrings,
    CallWithDuplicateResponsesResponse200,
    CallWithParametersRequest,
    CallWithResponseAndNoContentResponseResponse200,
    CallWithResponsesResponse200,
    ComplexParamsRequest,
    ComplexTypesResponse,
    DictionaryWithArray,
    Hey,
    Import,
    ImportRequest,
    ModelFromZendesk,
    ModelThatExtends,
    ModelThatExtendsExtends,
    ModelWithBoolean,
    ModelWithOneOfEnum,
    ModelWithReadOnlyAndWriteOnly,
    ModelWithString,
    ModelWithStringError,
    MultipartRequestRequest,
    NonAsciiResponse,
    OperationApiSimpleResponse200,
    PostCallWithOptionalParamRequest,
    PostCallWithOptionalParamResponse200,
    TypesResponse200,
    TypesResponse201,
    TypesResponse202,
    TypesResponse203,
    UploadFileResponse,
} from './hey.type.js'

/**
 * swagger
 */
export class Hey2 {
    public client: Got

    public constructor({
        prefixUrl = 'http://localhost:3000/base',
        options,
        client = got,
    }: {
        prefixUrl?: string | 'http://localhost:3000/base'
        options?: Options | OptionsInit
        client?: Got
    } = {}) {
        this.client = client.extend(
            ...[{ prefixUrl, throwHttpErrors: false }, options].filter((o): o is Options => o !== undefined),
        )
    }

    /**
     * GET /api/v{api-version}/simple/$count
     */
    public apiVVersionODataControllerCount({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'200', ModelFromZendesk>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/simple/$count`, {
                responseType: 'json',
            }),
            {
                200: ModelFromZendesk,
            },
        ) as ReturnType<this['apiVVersionODataControllerCount']>
    }

    /**
     * PUT /api/v{api-version}/defaults
     */
    public callToTestOrderOfParams({
        path,
        query,
    }: {
        path: { apiVersion: string }
        query?: {
            parameterOptionalStringWithDefault?: string
            parameterOptionalStringWithEmptyDefault?: string
            parameterOptionalStringWithNoDefault?: string
            parameterStringWithDefault: string
            parameterStringWithEmptyDefault: string
            parameterStringWithNoDefault: string
            parameterStringNullableWithNoDefault?: string
            parameterStringNullableWithDefault?: string
        }
    }) {
        return this.client.put(`api/v${path.apiVersion}/defaults`, {
            searchParams: query ?? {},
        })
    }

    /**
     * POST /api/v{api-version}/defaults
     */
    public callWithDefaultOptionalParameters({
        path,
        query,
    }: {
        path: { apiVersion: string }
        query?: {
            parameterString?: string
            parameterNumber?: string
            parameterBoolean?: string
            parameterEnum?: string
            parameterModel?: string
        }
    }) {
        return this.client.post(`api/v${path.apiVersion}/defaults`, {
            searchParams: query ?? {},
        })
    }

    /**
     * GET /api/v{api-version}/defaults
     */
    public callWithDefaultParameters({
        path,
        query,
    }: {
        path: { apiVersion: string }
        query?: {
            parameterString?: string
            parameterNumber?: string
            parameterBoolean?: string
            parameterEnum?: string
            parameterModel?: string
        }
    }) {
        return this.client.get(`api/v${path.apiVersion}/defaults`, {
            searchParams: query ?? {},
        })
    }

    /**
     * POST /api/v{api-version}/descriptions/
     */
    public callWithDescriptions({
        path,
        query,
    }: {
        path: { apiVersion: string }
        query?: {
            parameterWithBreaks?: string
            parameterWithBackticks?: string
            parameterWithSlashes?: string
            parameterWithExpressionPlaceholders?: string
            parameterWithQuotes?: string
            parameterWithReservedCharacters?: string
        }
    }) {
        return this.client.post(`api/v${path.apiVersion}/descriptions/`, {
            searchParams: query ?? {},
        })
    }

    /**
     * POST /api/v{api-version}/response
     */
    public callWithDuplicateResponses({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'203' | '204' | '205' | '206' | '207' | '208' | '226', ModelWithBoolean>
        | SuccessResponse<'200', CallWithDuplicateResponsesResponse200>
        | SuccessResponse<'201', ModelWithString>
        | SuccessResponse<'202', ModelWithString>
        | FailureResponse<'500', ModelWithStringError, 'response:statuscode'>
        | FailureResponse<'501', ModelWithStringError, 'response:statuscode'>
        | FailureResponse<'502', ModelWithStringError, 'response:statuscode'>
        | FailureResponse<'4XX', DictionaryWithArray, 'response:statuscode'>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<
              Exclude<StatusCode<1 | 3 | 4 | 5>, '500' | '501' | '502' | '4XX'>,
              unknown,
              'response:statuscode',
              IncomingHttpHeaders
          >
    > {
        return this.awaitResponse(
            this.client.post(`api/v${path.apiVersion}/response`, {
                responseType: 'json',
            }),
            {
                200: CallWithDuplicateResponsesResponse200,
                201: ModelWithString,
                202: ModelWithString,
                500: ModelWithStringError,
                501: ModelWithStringError,
                502: ModelWithStringError,
                '4XX': DictionaryWithArray,
                default: ModelWithBoolean,
            },
        ) as ReturnType<this['callWithDuplicateResponses']>
    }

    /**
     * GET /api/v{api-version}/no-content
     */
    public callWithNoContentResponse({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'204', unknown>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/no-content`, {
                responseType: 'text',
            }),
            {
                204: { parse: (x: unknown) => ({ right: x }) },
            },
        ) as ReturnType<this['callWithNoContentResponse']>
    }

    /**
     * POST /api/v{api-version}/parameters/{parameterPath}
     */
    public callWithParameters({
        body,
        path,
        query,
        headers,
    }: {
        body: CallWithParametersRequest
        path: { parameterPath: string; apiVersion: string }
        query?: { foo_ref_enum?: string; foo_all_of_enum: string; cursor: string }
        headers: { parameterHeader: string }
    }) {
        const _body = this.validateRequestBody(CallWithParametersRequest, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.client.post(`api/v${path.apiVersion}/parameters/${path.parameterPath}`, {
            json: _body.right,
            searchParams: query ?? {},
            headers: headers,
        })
    }

    /**
     * GET /api/v{api-version}/response
     */
    public callWithResponse({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<StatusCode<2>, Import>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/response`, {
                responseType: 'json',
            }),
            {
                default: Import,
            },
        ) as ReturnType<this['callWithResponse']>
    }

    /**
     * GET /api/v{api-version}/multiple-tags/response-and-no-content
     */
    public callWithResponseAndNoContentResponse({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'200', CallWithResponseAndNoContentResponseResponse200>
        | SuccessResponse<'204', unknown>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/multiple-tags/response-and-no-content`, {
                responseType: 'json',
            }),
            {
                200: CallWithResponseAndNoContentResponseResponse200,
                204: { parse: (x: unknown) => ({ right: x }) },
            },
        ) as ReturnType<this['callWithResponseAndNoContentResponse']>
    }

    /**
     * PUT /api/v{api-version}/response
     */
    public callWithResponses({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'203' | '204' | '205' | '206' | '207' | '208' | '226', ModelWithStringError>
        | SuccessResponse<'200', CallWithResponsesResponse200>
        | SuccessResponse<'201', ModelThatExtends>
        | SuccessResponse<'202', ModelThatExtendsExtends>
        | FailureResponse<'500', ModelWithStringError, 'response:statuscode'>
        | FailureResponse<'501', ModelWithStringError, 'response:statuscode'>
        | FailureResponse<'502', ModelWithStringError, 'response:statuscode'>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<
              Exclude<StatusCode<1 | 3 | 4 | 5>, '500' | '501' | '502'>,
              unknown,
              'response:statuscode',
              IncomingHttpHeaders
          >
    > {
        return this.awaitResponse(
            this.client.put(`api/v${path.apiVersion}/response`, {
                responseType: 'json',
            }),
            {
                200: CallWithResponsesResponse200,
                201: ModelThatExtends,
                202: ModelThatExtendsExtends,
                500: ModelWithStringError,
                501: ModelWithStringError,
                502: ModelWithStringError,
                default: ModelWithStringError,
            },
        ) as ReturnType<this['callWithResponses']>
    }

    /**
     * POST /api/v{api-version}/header
     */
    public callWithResultFromHeader({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'200', unknown>
        | FailureResponse<'400', unknown, 'response:statuscode'>
        | FailureResponse<'500', unknown, 'response:statuscode'>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<Exclude<StatusCode<1 | 3 | 4 | 5>, '400' | '500'>, unknown, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.post(`api/v${path.apiVersion}/header`, {
                responseType: 'text',
            }),
            {
                200: { parse: (x: unknown) => ({ right: x }) },
                400: { parse: (x: unknown) => ({ right: x }) },
                500: { parse: (x: unknown) => ({ right: x }) },
            },
        ) as ReturnType<this['callWithResultFromHeader']>
    }

    /**
     * POST /api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}
     */
    public callWithWeirdParameterNames({
        body,
        path,
        query,
        headers,
    }: {
        body: ModelWithString
        path: { parameterPath1: string; parameterPath2: string; parameterPath3: string; apiVersion: string }
        query?: { default?: string; 'parameter-query': string }
        headers: { 'parameter.header': string }
    }) {
        const _body = this.validateRequestBody(ModelWithString, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.client.post(
            `api/v${path.apiVersion}/parameters/${path.parameterPath1}/${path.parameterPath2}/${path.parameterPath3}`,
            {
                json: _body.right,
                searchParams: query ?? {},
                headers: headers,
            },
        )
    }

    /**
     * GET /api/v{api-version}/collectionFormat
     */
    public collectionFormat({
        path,
        query,
    }: {
        path: { apiVersion: string }
        query: {
            parameterArrayCSV: string
            parameterArraySSV: string
            parameterArrayTSV: string
            parameterArrayPipes: string
            parameterArrayMulti: string
        }
    }) {
        return this.client.get(`api/v${path.apiVersion}/collectionFormat`, {
            searchParams: query,
        })
    }

    /**
     * PUT /api/v{api-version}/complex/{id}
     */
    public complexParams({
        body,
        path,
    }: {
        body: ComplexParamsRequest
        path: { id: string; apiVersion: string }
    }): Promise<
        | SuccessResponse<'200', ModelWithString>
        | FailureResponse<undefined, unknown, 'request:body', undefined>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        const _body = this.validateRequestBody(ComplexParamsRequest, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.awaitResponse(
            this.client.put(`api/v${path.apiVersion}/complex/${path.id}`, {
                json: _body.right,
                responseType: 'json',
            }),
            {
                200: ModelWithString,
            },
        ) as ReturnType<this['complexParams']>
    }

    /**
     * GET /api/v{api-version}/complex
     */
    public complexTypes({
        path,
        query,
    }: {
        path: { apiVersion: string }
        query: { parameterObject: string; parameterReference: string }
    }): Promise<
        | SuccessResponse<'200', ComplexTypesResponse>
        | FailureResponse<'400', unknown, 'response:statuscode'>
        | FailureResponse<'500', unknown, 'response:statuscode'>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<Exclude<StatusCode<1 | 3 | 4 | 5>, '400' | '500'>, unknown, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/complex`, {
                searchParams: query,
                responseType: 'json',
            }),
            {
                200: ComplexTypesResponse,
                400: { parse: (x: unknown) => ({ right: x }) },
                500: { parse: (x: unknown) => ({ right: x }) },
            },
        ) as ReturnType<this['complexTypes']>
    }

    /**
     * POST /api/v{api-version}/formData/
     */
    public createApiFormDatum({
        body,
        path,
        query,
    }: {
        body: ModelWithString
        path: { apiVersion: string }
        query?: { parameter?: string }
    }) {
        const _body = this.validateRequestBody(ModelWithString, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.client.post(`api/v${path.apiVersion}/formData/`, {
            form: _body.right,
            searchParams: query ?? {},
        })
    }

    /**
     * POST /api/v{api-version}/requestBody/
     */
    public createApiRequestBody({
        body,
        path,
        query,
    }: {
        body: ModelWithString
        path: { apiVersion: string }
        query?: { parameter?: string }
    }) {
        const _body = this.validateRequestBody(ModelWithString, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.client.post(`api/v${path.apiVersion}/requestBody/`, {
            json: _body.right,
            searchParams: query ?? {},
        })
    }

    /**
     * DELETE /api/v{api-version}/simple
     */
    public deleteCallWithoutParametersAndResponse({ path }: { path: { apiVersion: string } }) {
        return this.client.delete(`api/v${path.apiVersion}/simple`)
    }

    /**
     * DELETE /api/v{api-version}/foo/{foo_param}/bar/{BarParam}
     */
    public deleteFoo({
        path,
        headers,
    }: {
        path: { fooParam: string; barParam: string; apiVersion: string }
        headers: { 'x-Foo-Bar': string }
    }) {
        return this.client.delete(`api/v${path.apiVersion}/foo/${path.fooParam}/bar/${path.barParam}`, {
            headers: headers,
        })
    }

    /**
     * POST /api/v{api-version}/parameters/deprecated
     *
     * @deprecated
     */
    public deprecatedCall({ path, headers }: { path: { apiVersion: string }; headers: { parameter: string } }) {
        return this.client.post(`api/v${path.apiVersion}/parameters/deprecated`, {
            headers: headers,
        })
    }

    /**
     * GET /api/v{api-version}/multiple-tags/a
     */
    public dummyA({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'200', Hey>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/multiple-tags/a`, {
                responseType: 'json',
            }),
            {
                200: Hey,
            },
        ) as ReturnType<this['dummyA']>
    }

    /**
     * GET /api/v{api-version}/multiple-tags/b
     */
    public dummyB({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'204', unknown>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/multiple-tags/b`, {
                responseType: 'text',
            }),
            {
                204: { parse: (x: unknown) => ({ right: x }) },
            },
        ) as ReturnType<this['dummyB']>
    }

    /**
     * GET /api/v{api-version}/duplicate
     */
    public getDuplicateName({ path }: { path: { apiVersion: string } }) {
        return this.client.get(`api/v${path.apiVersion}/duplicate`)
    }

    /**
     * PUT /api/v{api-version}/duplicate
     */
    public putDuplicateName({ path }: { path: { apiVersion: string } }) {
        return this.client.put(`api/v${path.apiVersion}/duplicate`)
    }

    /**
     * POST /api/v{api-version}/duplicate
     */
    public postDuplicateName({ path }: { path: { apiVersion: string } }) {
        return this.client.post(`api/v${path.apiVersion}/duplicate`)
    }

    /**
     * DELETE /api/v{api-version}/duplicate
     */
    public deleteDuplicateName({ path }: { path: { apiVersion: string } }) {
        return this.client.delete(`api/v${path.apiVersion}/duplicate`)
    }

    /**
     * GET /api/v{api-version}/no+tag
     */
    public export({ path }: { path: { apiVersion: string } }) {
        return this.client.get(`api/v${path.apiVersion}/no+tag`)
    }

    /**
     * GET /api/v{api-version}/file/{id}
     */
    public fileResponse({
        path,
    }: {
        path: { id: string; apiVersion: string }
    }): Promise<
        | SuccessResponse<'200', unknown>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/file/${path.id}`, {
                responseType: 'text',
            }),
            {
                200: { parse: (x: unknown) => ({ right: x }) },
            },
        ) as ReturnType<this['fileResponse']>
    }

    /**
     * PUT /api/v{api-version}/no+tag
     */
    public fooWow({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.put(`api/v${path.apiVersion}/no+tag`, {
                responseType: 'text',
            }),
            {},
        ) as ReturnType<this['fooWow']>
    }

    /**
     * GET /api/v{api-version}/parameters/
     */
    public getCallWithOptionalParam({
        body,
        path,
        query,
    }: {
        body: ModelWithOneOfEnum
        path: { apiVersion: string }
        query?: { page?: string }
    }) {
        const _body = this.validateRequestBody(ModelWithOneOfEnum, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.client.get(`api/v${path.apiVersion}/parameters/`, {
            json: _body.right,
            searchParams: query ?? {},
        })
    }

    /**
     * GET /api/v{api-version}/simple
     */
    public getCallWithoutParametersAndResponse({ path }: { path: { apiVersion: string } }) {
        return this.client.get(`api/v${path.apiVersion}/simple`)
    }

    /**
     * HEAD /api/v{api-version}/simple
     */
    public headCallWithoutParametersAndResponse({ path }: { path: { apiVersion: string } }) {
        return this.client(`api/v${path.apiVersion}/simple`, {
            method: 'HEAD',
        })
    }

    /**
     * POST /api/v{api-version}/no+tag
     */
    public import({
        body,
        path,
    }: {
        body: ImportRequest
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'201' | '202' | '203' | '204' | '205' | '206' | '207' | '208' | '226', ModelWithReadOnlyAndWriteOnly>
        | SuccessResponse<'200', ModelFromZendesk>
        | FailureResponse<undefined, unknown, 'request:body', undefined>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        const _body = this.validateRequestBody(ImportRequest, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.awaitResponse(
            this.client.post(`api/v${path.apiVersion}/no+tag`, {
                json: _body.right,
                responseType: 'json',
            }),
            {
                200: ModelFromZendesk,
                default: ModelWithReadOnlyAndWriteOnly,
            },
        ) as ReturnType<this['import']>
    }

    /**
     * POST /api/v{api-version}/multipart
     */
    public multipartRequest({ body, path }: { body: MultipartRequestRequest; path: { apiVersion: string } }) {
        const _body = this.validateRequestBody(MultipartRequestRequest, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.client.post(`api/v${path.apiVersion}/multipart`, {
            form: _body.right,
        })
    }

    /**
     * GET /api/v{api-version}/multipart
     */
    public multipartResponse({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'200', unknown>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/multipart`, {
                responseType: 'text',
            }),
            {
                200: { parse: (x: unknown) => ({ right: x }) },
            },
        ) as ReturnType<this['multipartResponse']>
    }

    /**
     * POST /api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串
     */
    public nonAscii({
        path,
        query,
    }: {
        path: { apiVersion: string }
        query: { nonAsciiParamæøåÆØÅöôêÊ: string }
    }): Promise<
        | SuccessResponse<'200', NonAsciiResponse>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.post(`api/v${path.apiVersion}/non-ascii-æøåÆØÅöôêÊ字符串`, {
                searchParams: query,
                responseType: 'json',
            }),
            {
                200: NonAsciiResponse,
            },
        ) as ReturnType<this['nonAscii']>
    }

    /**
     * GET /api/v{api-version}/simple:operation
     */
    public operationApiSimple({
        path,
    }: {
        path: { fooParam: string; apiVersion: string }
    }): Promise<
        | SuccessResponse<'201' | '202' | '203' | '204' | '205' | '206' | '207' | '208' | '226', ModelWithBoolean>
        | SuccessResponse<'200', OperationApiSimpleResponse200>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/simple:operation`, {
                responseType: 'json',
            }),
            {
                200: OperationApiSimpleResponse200,
                default: ModelWithBoolean,
            },
        ) as ReturnType<this['operationApiSimple']>
    }

    /**
     * OPTIONS /api/v{api-version}/simple
     */
    public optionsCallWithoutParametersAndResponse({ path }: { path: { apiVersion: string } }) {
        return this.client(`api/v${path.apiVersion}/simple`, {
            method: 'OPTIONS',
        })
    }

    /**
     * PATCH /api/v{api-version}/no+tag
     */
    public patchApiNoTag({
        path,
    }: {
        path: { apiVersion: string }
    }): Promise<
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.patch(`api/v${path.apiVersion}/no+tag`, {
                responseType: 'text',
            }),
            {},
        ) as ReturnType<this['patchApiNoTag']>
    }

    /**
     * PATCH /api/v{api-version}/simple
     */
    public patchCallWithoutParametersAndResponse({ path }: { path: { apiVersion: string } }) {
        return this.client.patch(`api/v${path.apiVersion}/simple`)
    }

    /**
     * POST /api/v{api-version}/parameters/
     */
    public postCallWithOptionalParam({
        body,
        path,
        query,
    }: {
        body: PostCallWithOptionalParamRequest
        path: { apiVersion: string }
        query: { parameter: string }
    }): Promise<
        | SuccessResponse<'200', PostCallWithOptionalParamResponse200>
        | SuccessResponse<'204', unknown>
        | FailureResponse<undefined, unknown, 'request:body', undefined>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        const _body = this.validateRequestBody(PostCallWithOptionalParamRequest, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.awaitResponse(
            this.client.post(`api/v${path.apiVersion}/parameters/`, {
                json: _body.right,
                searchParams: query,
                responseType: 'json',
            }),
            {
                200: PostCallWithOptionalParamResponse200,
                204: { parse: (x: unknown) => ({ right: x }) },
            },
        ) as ReturnType<this['postCallWithOptionalParam']>
    }

    /**
     * POST /api/v{api-version}/simple
     */
    public postCallWithoutParametersAndResponse({ path }: { path: { apiVersion: string } }) {
        return this.client.post(`api/v${path.apiVersion}/simple`)
    }

    /**
     * PUT /api/v{api-version}/simple
     */
    public putCallWithoutParametersAndResponse({ path }: { path: { apiVersion: string } }) {
        return this.client.put(`api/v${path.apiVersion}/simple`)
    }

    /**
     * PUT /api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串
     *
     * Login User
     */
    public putWithFormUrlEncoded({ body, path }: { body: ArrayWithStrings; path: { apiVersion: string } }) {
        const _body = this.validateRequestBody(ArrayWithStrings, body)
        if ('left' in _body) {
            return Promise.resolve(_body)
        }

        return this.client.put(`api/v${path.apiVersion}/non-ascii-æøåÆØÅöôêÊ字符串`, {
            form: _body.right,
        })
    }

    /**
     * POST /api/v{api-version}/error
     */
    public testErrorCode({
        path,
        query,
    }: {
        path: { apiVersion: string }
        query: { status: string }
    }): Promise<
        | SuccessResponse<'200', unknown>
        | FailureResponse<'500', unknown, 'response:statuscode'>
        | FailureResponse<'501', unknown, 'response:statuscode'>
        | FailureResponse<'502', unknown, 'response:statuscode'>
        | FailureResponse<'503', unknown, 'response:statuscode'>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<
              Exclude<StatusCode<1 | 3 | 4 | 5>, '500' | '501' | '502' | '503'>,
              unknown,
              'response:statuscode',
              IncomingHttpHeaders
          >
    > {
        return this.awaitResponse(
            this.client.post(`api/v${path.apiVersion}/error`, {
                searchParams: query,
                responseType: 'text',
            }),
            {
                200: { parse: (x: unknown) => ({ right: x }) },
                500: { parse: (x: unknown) => ({ right: x }) },
                501: { parse: (x: unknown) => ({ right: x }) },
                502: { parse: (x: unknown) => ({ right: x }) },
                503: { parse: (x: unknown) => ({ right: x }) },
            },
        ) as ReturnType<this['testErrorCode']>
    }

    /**
     * GET /api/v{api-version}/types
     */
    public types({
        path,
        query,
    }: {
        path: { id: string; apiVersion: string }
        query: {
            parameterNumber: string
            parameterString: string
            parameterBoolean: string
            parameterObject: string
            parameterArray: string
            parameterDictionary: string
            parameterEnum: string
            parameterTuple: string
        }
    }): Promise<
        | SuccessResponse<'200', TypesResponse200>
        | SuccessResponse<'201', TypesResponse201>
        | SuccessResponse<'202', TypesResponse202>
        | SuccessResponse<'203', TypesResponse203>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.get(`api/v${path.apiVersion}/types`, {
                searchParams: query,
                responseType: 'json',
            }),
            {
                200: TypesResponse200,
                201: TypesResponse201,
                202: TypesResponse202,
                203: TypesResponse203,
            },
        ) as ReturnType<this['types']>
    }

    /**
     * POST /api/v{api-version}/upload
     */
    public uploadFile({
        body,
        path,
    }: {
        body: FormData
        path: { apiVersion: string }
    }): Promise<
        | SuccessResponse<'200', UploadFileResponse>
        | FailureResponse<StatusCode<2>, string, 'response:body', IncomingHttpHeaders>
        | FailureResponse<StatusCode<1 | 3 | 4 | 5>, string, 'response:statuscode', IncomingHttpHeaders>
    > {
        return this.awaitResponse(
            this.client.post(`api/v${path.apiVersion}/upload`, {
                form: body,
                responseType: 'json',
            }),
            {
                200: UploadFileResponse,
            },
        ) as ReturnType<this['uploadFile']>
    }

    public validateRequestBody<Body>(
        parser: { parse: (o: unknown) => { left: DefinedError[] } | { right: Body } },
        body: unknown,
    ) {
        const _body = parser.parse(body)
        if ('left' in _body) {
            return {
                success: false as const,
                statusCode: undefined,
                status: undefined,
                headers: undefined,
                left: body,
                validationErrors: _body.left,
                where: 'request:body',
            } satisfies FailureResponse<undefined, unknown, 'request:body', undefined>
        }
        return _body
    }

    public async awaitResponse<
        I,
        S extends Record<PropertyKey, { parse: (o: I) => { left: DefinedError[] } | { right: unknown } }>,
    >(response: CancelableRequest<NoInfer<Response<I>>>, schemas: S) {
        const result = await response
        const status =
            result.statusCode < 200
                ? 'informational'
                : result.statusCode < 300
                  ? 'success'
                  : result.statusCode < 400
                    ? 'redirection'
                    : result.statusCode < 500
                      ? 'client-error'
                      : 'server-error'
        const validator = schemas[result.statusCode] ?? schemas.default
        const body = validator?.parse?.(result.body)
        if (result.statusCode < 200 || result.statusCode >= 300) {
            return {
                success: false as const,
                statusCode: result.statusCode.toString(),
                status,
                headers: result.headers,
                left: body !== undefined && 'right' in body ? body.right : result.body,
                validationErrors: body !== undefined && 'left' in body ? body.left : undefined,
                where: 'response:statuscode',
            }
        }
        if (body === undefined || 'left' in body) {
            return {
                success: body === undefined,
                statusCode: result.statusCode.toString(),
                status,
                headers: result.headers,
                left: result.body,
                validationErrors: body?.left,
                where: 'response:body',
            }
        }
        return {
            success: true as const,
            statusCode: result.statusCode.toString(),
            status,
            headers: result.headers,
            right: result.body,
        }
    }
}

export type Status<Major> = Major extends string
    ? Major extends `1${number}`
        ? 'informational'
        : Major extends `2${number}`
          ? 'success'
          : Major extends `3${number}`
            ? 'redirection'
            : Major extends `4${number}`
              ? 'client-error'
              : 'server-error'
    : undefined
export interface SuccessResponse<StatusCode extends string, T> {
    success: true
    statusCode: StatusCode
    status: Status<StatusCode>
    headers: IncomingHttpHeaders
    right: T
}
export interface FailureResponse<StatusCode = string, T = unknown, Where = never, Headers = IncomingHttpHeaders> {
    success: false
    statusCode: StatusCode
    status: Status<StatusCode>
    headers: Headers
    validationErrors: DefinedError[] | undefined
    left: T
    where: Where
}
export type StatusCode<Major extends number = 1 | 2 | 3 | 4 | 5> = `${Major}${number}`
