/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import type { ValidateFunction } from 'ajv'
import { ValidationError } from 'ajv'

export type Simple = number | Simple[]

export const Simple = {
    validate: (await import('./schemas/simple.schema.js')).validate as ValidateFunction<Simple>,
    get schema() {
        return Simple.validate.schema
    },
    get errors() {
        return Simple.validate.errors ?? undefined
    },
    is: (o: unknown): o is Simple => Simple.validate(o) === true,
    assert: (o: unknown) => {
        if (!Simple.validate(o)) {
            throw new ValidationError(Simple.errors ?? [])
        }
    },
} as const
