/**
 * Generated by @zefiros-software/therefore@v0.0.1
 * Do not manually touch this
 */
/* eslint-disable */
import AjvValidator from 'ajv'
import type { ValidateFunction } from 'ajv'

export interface Person {
    /**
     * The person's first name.
     */
    firstName: string
    lastName: string
    age: number
}

export const Person = {
    validate: require('./schemas/person.schema.js') as ValidateFunction<Person>,
    get schema() {
        return Person.validate.schema
    },
    source: `${__dirname}example.schema`,
    sourceSymbol: 'person',
    is: (o: unknown): o is Person => Person.validate(o) === true,
    assert: (o: unknown) => {
        if (!Person.validate(o)) {
            throw new AjvValidator.ValidationError(Person.validate.errors ?? [])
        }
    },
} as const
