/**
 * Generated by Ajv https://ajv.js.org/guide/managing-schemas.html#standalone-validation-code 
 * eslint-disable
 */
const o={$schema:"http://json-schema.org/draft-07/schema#",title:"getApodResponse",type:"array",items:{}};function r(e,{instancePath:a="",parentData:p,parentDataProperty:y,rootData:m=e}={}){let s=null,t=0;return t===0&&!Array.isArray(e)?(r.errors=[{instancePath:a,schemaPath:"#/type",keyword:"type",params:{type:"array"},message:"must be array"}],!1):(r.errors=s,t===0)}r.schema=o;export{r as validate10};
