/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface Group {
    description: string
    members: User[]
}

export interface Person {
    name: string
}

export interface Query {
    allUsers: User[]
    me: User
    person: Person
}

export interface User {
    name: string
    groups: Group[]
}
