/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface Group {
    description: string
    members: User[]
}

export interface Person {
    name: string
}

export type User = Omit<Person, 'name'> & {
    groups: Group[]
    name: string
}
