/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface CreateEmployeeInput {
    /**
     * @default 'user_1'
     */
    employee: string
    firstName: string
    lastName: string
    officeName: string
    title: string
    team: 'development' | 'marketing' | 'finance' | 'product' | 'cool cats and kittens'
    salary: string
    manager: string
    dateHired: string
    birthday: string
}

export interface CreateOfficeInput {
    gsi1pk: string
    gsi1sk: string
    gsi2pk: string
    gsi2sk: string
    gsi3pk: string
    gsi3sk: string
    gsi4pk: string
    gsi4sk: string
    gsi5pk: string
    gsi5sk: string
    officeName: string
    country: string
    state: string
    city: string
    zip: string
    address: string
}

export interface CreateTaskInput {
    gsi1pk: string
    gsi1sk: string
    gsi2pk: string
    gsi2sk: string
    gsi3pk: string
    gsi3sk: string
    gsi4pk: string
    gsi4sk: string
    gsi5pk: string
    gsi5sk: string
    task: string
    project: string
    employee: string
    description?: string | undefined
    /**
     * @default 'open'
     */
    status: 'open' | 'in-progress' | 'closed'
    points: number
    comments?: unknown
}
