/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import type { ValidateFunction } from 'ajv'

export type GetApodResponse = unknown[]

export const GetApodResponse = {
    validate: (await import('./schemas/get-apod-response.schema.js')).validate10 as unknown as ValidateFunction<GetApodResponse>,
    get schema() {
        return GetApodResponse.validate.schema
    },
    get errors() {
        return GetApodResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is GetApodResponse => GetApodResponse.validate(o) === true,
} as const
