/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
// biome-ignore-all lint: this file is generated
/* eslint-disable */

import { z } from 'zod'

export const ConvertApiRequest = z.object({
    url: z.string().optional(),
})

export type ConvertApiRequest = z.infer<typeof ConvertApiRequest>

export const ConvertApiResponse = z.object({})

export type ConvertApiResponse = z.infer<typeof ConvertApiResponse>
